apiVersion: v1
kind: Pod
metadata:
  name: debug-alpine
  namespace: postgresql
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /home/venv
      name: postgres-data-volume
  volumes:
  - name: postgres-data-volume
    persistentVolumeClaim:
      claimName: postgres-data-postgres-0
  restartPolicy: Never