apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni-config
  namespace: test
data:
  config.yml: |
    scope: batman
    name: patroni-0.patroni.test.svc.cluster.local

    restapi:
      listen: 0.0.0.0:8008
      connect_address: patroni-0.patroni.test.svc.cluster.local:8008

    raft:
      data_dir: raft
      self_addr: patroni-0.patroni.test.svc.cluster.local:2222

    bootstrap:
      dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
          use_pg_rewind: true
          pg_hba:
            - host replication replicator 0.0.0.0/0 md5
            - host all all 0.0.0.0/0 md5
          parameters:

      initdb:
      - encoding: UTF8
      - data-checksums

    postgresql:
      listen: 0.0.0.0:5432
      connect_address: patroni-0.patroni.test.svc.cluster.local:5432

      data_dir: data/postgresql0
      pgpass: /tmp/pgpass0
      authentication:
        replication:
          username: replicator
          password: rep-pass
        superuser:
          username: postgres
          password: <my_password>
        rewind:  # Has no effect on postgres 10 and lower
          username: rewind_user
          password: rewind_password
      parameters:
        unix_socket_directories: '..'

    tags:
        noloadbalance: false
        clonefrom: false
        nostream: false