apiVersion: v1
kind: Service
metadata:
  name: patroni
  namespace: test
spec:
  selector:
    app: patroni
  type: ClusterIP
  ports:
  - name: patroni
    protocol: TCP
    port: 5432
    targetPort: 5432