name: postgres-0
scope: postgres

raft:
  data_dir: raft
  self_addr: postgres-2:2222
restapi:
  listen: 0.0.0.0:8000
  connect_address: postgres-2:8000

postgresql:
  listen: 0.0.0.0:5432
  connect_address: postgres-2:5432
  data_dir: data/postgresql2
  pgpass: /tmp/pgpass2
  authentication:
    replication:
      username: replicator
      password: postgres
    superuser:
      username: postgres
      password: postgres
    rewind:
      username: postgres
      password: postgres
  parameters:
    unix_socket_directories: '..'

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      pg_hba:
        - host replication replicator 0.0.0.0/0 md5
        - host all all 0.0.0.0/0 md5
      parameters:
  initdb:
  - encoding: UTF8
  - data-checksums

tags:
    noloadbalance: false
    clonefrom: false
    nostream: false