apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni
data:
  init-job: |
    {{ include "init-job-script" . | nindent 4 }}
  init-generator-script: |
    {{ include "init-generator-script" . | nindent 4 }}
  baseconfig: |
    {{ include "baseconfig" . | nindent 4 }}