apiVersion: v1
kind: Service
metadata:
  name: {{ include "patroni-chart.fullname" . }}
  labels:
    {{- include "patroni-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: {{- range .Values.service.ports }}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
    name: {{ .name }}
  {{- end }}
  selector:
    {{- include "patroni-chart.selectorLabels" . | nindent 4 }}
