apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "patroni-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "patroni-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      securityContext:
      {{- toYaml .Values.securityContext.global | nindent 8 }}
      initContainers:
      - name: init-data-dir
        image: busybox
        env:
          - name: MY_POD_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POSTGRES_PASSWORD
            value: {{ .Values.POSTGRES_PASSWORD }}
          - name: POSTGRES_USER
            value: {{ .Values.POSTGRES_USER }}
          - name: REPLICATION_PASSWORD
            value: {{ .Values.REPLICATION_PASSWORD }}
          - name: REPLICATION_USER
            value: {{ .Values.REPLICATION_USER }}
          - name: REWIND_PASSWORD
            value: {{ .Values.REWIND_PASSWORD }}
          - name: REWIND_USER
            value: {{ .Values.REWIND_USER }}
        {{- if .Values.initContainers.extraEnv }}
          {{- toYaml .Values.initContainers.extraEnv | nindent 10 }}
        {{- end }}
        command: {{ toYaml .Values.initContainers.command | nindent 8 }}
        volumeMounts:
        {{- with .Values.initContainers.volumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: postgres-data
          mountPath: /home/venv/data
        - name: patroni-config-baseconfig
          mountPath: /home/venv/baseconfig.yml
          subPath: baseconfig
        - name: patroni-config-init-generator-script
          mountPath: /home/venv/generator.sh
          subPath: init-generator-script
        - name: shared-config-volume
          mountPath: /home/venv/config
        securityContext:
        {{- toYaml .Values.securityContext.initContainers | nindent 10 }}
      containers:
      - name: patroni
        imagePullPolicy: Always
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        env:
        {{- if .Values.patroni.extraEnv }}
          {{- toYaml .Values.patroni.extraEnv | nindent 10 }}
        {{- end }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.POSTGRES_PASSWORD }}
          - name: POSTGRES_USER
            value: {{ .Values.POSTGRES_USER }}
          - name: REPLICATION_PASSWORD
            value: {{ .Values.REPLICATION_PASSWORD }}
          - name: REPLICATION_USER
            value: {{ .Values.REPLICATION_USER }}
          - name: REWIND_PASSWORD
            value: {{ .Values.REWIND_PASSWORD }}
          - name: REWIND_USER
            value: {{ .Values.REWIND_USER }}
          - name: MY_POD_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 5432
          name: postgres-0
        - containerPort: 5433
          name: postgres-1
        - containerPort: 5434
          name: postgres-2
        - containerPort: 2222
          name: raft-0
        - containerPort: 2223
          name: raft-1
        - containerPort: 2224
          name: raft-2
        - containerPort: 8000
          name: restapi-0
        - containerPort: 8001
          name: restapi-1
        - containerPort: 8002
          name: restapi-2
        {{- if .Values.patroni.extraPorts }}
          {{- with .Values.patroni.extraPorts }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
        volumeMounts:    
        {{- if .Values.extraVolumeMounts }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
        - name: postgres-data
          mountPath: /home/venv/data
        - name: raft-data
          mountPath: /home/venv/raft
        - name: patroni-config-baseconfig
          mountPath: /home/venv/baseconfig.yml
          subPath: baseconfig
        - name: patroni-config-init-generator-script
          mountPath: /home/venv/generator.sh
          subPath: init-generator-script
        - name: shared-config-volume
          mountPath: /home/venv/config
        command: {{ toYaml .Values.patroni.command | nindent 8 }}
        securityContext:
        {{- toYaml .Values.securityContext.patroni | nindent 10 }}
      volumes:
      {{- if .Values.extraVolumes }}
          {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
      - name: shared-config-volume
        emptyDir: {}
      - name: patroni-config-init-generator-script
        configMap:
          name: patroni
      - name: patroni-config-baseconfig
        configMap:
          name: patroni

  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.pvc.storageClassName }}
      resources: {{ toYaml .Values.pvc.postgres.resources | nindent 8 }}
  - metadata:
      name: raft-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.pvc.storageClassName }}
      resources: {{ toYaml .Values.pvc.raft.resources | nindent 8 }}